openapi: 3.0.0
info:
  title: Super Duper Train Delay Prediction API
  description: Predict train delays.
  version: v1.0
paths:
  /predict:
    post:
      operationId: api_connexxion.predict
      summary: Returns train delay predictions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
      responses:
        '200':
          description: An object that contains the requested predictions (+ metadata)
          content:
            application/json:
              schema:
                type: object