openapi: 3.0.0
info:
  title: Super Duper API
  description: Predict train delays.
  version: v1.0
paths:
  /predict:
    post:
      operationId: api_connexxion.predict
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array